### ISSUE TITLE
Can you write some blog/steps how you have compiled SCIP to WASM?

### ISSUE THREAD

**Issue by airen1986** [jstrieb/poker-chipper#1]
Hi,

Can you write some blog/steps how you have compiled SCIP to WASM?

Thanks

**Comment by jstrieb** [comment]
Hey @airen1986! If you're looking to use the WASM version of SCIP in your own projects, feel free to use the files I have already compiled here.

https://github.com/jstrieb/poker-chipper/tree/a978ea3d49b8c4c17e6a4865f03d6f215ca8456a/src/compiled

The process to compile those files is documented in `experiments/Dockerfile` in the repo. 

https://github.com/jstrieb/poker-chipper/blob/a978ea3d49b8c4c17e6a4865f03d6f215ca8456a/experiments/Dockerfile#L1-L59

As for how I figured out what flags to use when compiling SCIP with emscripten, I noticed an argument in the `CMakeLists.txt` file in the tarball I build SCIP from that lets it build with no external code. This makes compilation easier since no external libraries need to be compiled for WASM in order for the core part of SCIP to work.

```
if(NOT NO_EXTERNAL_CODE)
   option(AUTOBUILD "find and use dependencies on availability (ignores PAPILO, IPOPT, ZLIB, GMP, PAPILO, ZIMPL, READLINE, WORHP flags)" OFF)
   option(PAPILO "should papilo library be linked" ON)
   option(ZIMPL "should zimpl be linked" ON)
   option(GMP "should GMP be linked" ON)
   option(GCG "should GCG be included" ON)
   option(UG "should ug be included" ON)
   option(BOOST "Use Boost (required to build the binary). Disable if you only want to build libsoplex." ON)
else()
   option(PAPILO "should papilo library be linked" OFF)
   option(ZIMPL "should zimpl be linked" OFF)
   option(GMP "should GMP be linked" OFF)
   option(GCG "should GCG be included" OFF)
   option(UG "should ug be included" OFF)
   option(ZLIB "should zlib be linked" OFF)
   option(READLINE "should readline be linked" OFF)
   option(IPOPT "should ipopt be linked" OFF)
   option(WORHP "should worhp be linked" OFF)
   option(BOOST "Use Boost (required to build the binary). Disable if you only want to build libsoplex." OFF)
   option(QUADMATH "should quadmath library be used" OFF)
   option(MPFR "Use MPFR" OFF)
   set(SYM none CACHE STRING "options for symmetry computation")
endif()
```

Unfortunately, I cannot find this `CMakeLists.txt` file in the [core SCIP GitHub Repository](https://github.com/scipopt/scip), so I don't know where that file lives before it gets added to the tarball.

The emscripten-specific flags, I pulled out of `emscripten/src/settings.js` in the Emscripten repo. Some of the flags are documented on the Emscripten website, but I believe some of them are not.

https://github.com/emscripten-core/emscripten/blob/1171adaa21048ba8dc82169b9d79952e8754b201/src/settings.js#L1-L21

Hope this helps!

**Comment by airen1986** [comment]
Thank you @jstrieb , it helped a lot !

**Comment by jstrieb** [comment]
Hi again @airen1986! 

I've been intending to write this up for a while, and your question was good motivation to bump it up on my to do list, and finally do it.

[I've posted a much more detailed, comprehensive version of my comment above to my website.](https://jstrieb.github.io/posts/scip-wasm/) If what I wrote before was helpful, hopefully this post is even more so!
